/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cadastro;

import View.jTableModel.NovoEquipamento_jTableModel;
import Entidades.Equipamento;
import PersistenciaLista.EquipamentoPersistenciaLista;
import javax.swing.JOptionPane;
import Persistencia.persistenciaEquipamento;

/**
 *
 * @author pascal
 */
public class CadastrarEquipamentos extends javax.swing.JPanel {
    private static persistenciaEquipamento banco = new EquipamentoPersistenciaLista ();

    /**
     * Creates new form CadastrarEquipamentos
     */
    public CadastrarEquipamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Descricao_jTextPane = new javax.swing.JTextPane();
        Cancelar_jButton = new javax.swing.JButton();
        Salvar_jButton = new javax.swing.JButton();
        Fire_jTextField = new javax.swing.JTextField();
        Water_jTextField = new javax.swing.JTextField();
        Air_jTextField = new javax.swing.JTextField();
        Rock_jTextField = new javax.swing.JTextField();
        Defesa_jTextField = new javax.swing.JTextField();
        Ataque_jTextField = new javax.swing.JTextField();
        Level_jTextField = new javax.swing.JTextField();
        Raridade_jTextField = new javax.swing.JTextField();
        tipo_jTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        preco_jTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Equipamento_jTable = new javax.swing.JTable();
        Apagar_jButton = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tipo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Level Mínimo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ataque");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Defesa");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Magia");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Raridade");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Descrição");

        jLabel8.setText("Fogo");

        jLabel9.setText("Agua");

        jLabel10.setText("Terra");

        jLabel11.setText("Ar");

        jScrollPane3.setViewportView(Descricao_jTextPane);

        Cancelar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar_jButton.setText("Cancelar");
        Cancelar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButtonActionPerformed(evt);
            }
        });

        Salvar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salvar_jButton.setText("Salvar");
        Salvar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_jButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Preço");

        preco_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preco_jTextFieldActionPerformed(evt);
            }
        });

        Equipamento_jTable.setModel(new NovoEquipamento_jTableModel(banco.getAll()) );
        jScrollPane1.setViewportView(Equipamento_jTable);

        Apagar_jButton.setText("Apagar");
        Apagar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apagar_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(tipo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Level_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ataque_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Raridade_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(Defesa_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addComponent(preco_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel8)
                .addGap(77, 77, 77)
                .addComponent(jLabel9)
                .addGap(65, 65, 65)
                .addComponent(jLabel10)
                .addGap(90, 90, 90)
                .addComponent(jLabel11))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Fire_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Water_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Rock_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Air_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(Cancelar_jButton)
                .addGap(157, 157, 157)
                .addComponent(Salvar_jButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Apagar_jButton)
                .addGap(139, 139, 139)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1))
                    .addComponent(tipo_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Level_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(Ataque_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Raridade_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addComponent(Defesa_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(preco_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fire_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Water_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rock_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Air_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar_jButton)
                    .addComponent(Salvar_jButton))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Apagar_jButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Salvar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_jButtonActionPerformed
       Equipamento novo_equip = new Equipamento();
       novo_equip.setTipo(tipo_jTextField.getText());
       double preco = Double.parseDouble(preco_jTextField.getText());
       novo_equip.setPreco(preco);
       int atk = Integer.parseInt(Ataque_jTextField.getText());
       novo_equip.setAtk(atk);
       int def = Integer.parseInt(Defesa_jTextField.getText());
       novo_equip.setDef(def);
       novo_equip.setRaridade(Raridade_jTextField.getText());
       int nivel = Integer.parseInt(Level_jTextField.getText());
       novo_equip.setNivelminimo(nivel);
       int fire = Integer.parseInt(Fire_jTextField.getText());
       novo_equip.setMagiaFire(fire);
       int water = Integer.parseInt(Water_jTextField.getText());
       novo_equip.setMagiaWater(water);
       int rock = Integer.parseInt(Rock_jTextField.getText());
       novo_equip.setMagiaRock(rock);
       int air = Integer.parseInt(Air_jTextField.getText());
       novo_equip.setMagiaAir(air);
       novo_equip.setDescricao(Descricao_jTextPane.getText());
       
       banco.inserir(novo_equip);
       JOptionPane.showMessageDialog(
               Salvar_jButton, "Cadastrado com Sucesso!");
        Cancelar_jButtonActionPerformed(null);
        NovoEquipamento_jTableModel modelo = 
        (NovoEquipamento_jTableModel) Equipamento_jTable.getModel();
        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_Salvar_jButtonActionPerformed

    private void Cancelar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancelar_jButtonActionPerformed

    private void preco_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preco_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preco_jTextFieldActionPerformed

    private void Apagar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apagar_jButtonActionPerformed
        int[] linhas = Equipamento_jTable.getSelectedRows();
        
//        int decremento = 0;
//        for(int i = 0; i < linhas.length;i++){
//            Responsavel removido = banco
//                    .getAll().get(linhas[i]-decremento);
        for(int i = linhas.length - 1; i >= 0;i--){
            Equipamento removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);
//            decremento++;
            
            NovoEquipamento_jTableModel modelo = 
                (NovoEquipamento_jTableModel) Equipamento_jTable.getModel();
        
            modelo.fireTableRowsDeleted(0, 1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Apagar_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Air_jTextField;
    private javax.swing.JButton Apagar_jButton;
    private javax.swing.JTextField Ataque_jTextField;
    private javax.swing.JButton Cancelar_jButton;
    private javax.swing.JTextField Defesa_jTextField;
    private javax.swing.JTextPane Descricao_jTextPane;
    private javax.swing.JTable Equipamento_jTable;
    private javax.swing.JTextField Fire_jTextField;
    private javax.swing.JTextField Level_jTextField;
    private javax.swing.JTextField Raridade_jTextField;
    private javax.swing.JTextField Rock_jTextField;
    private javax.swing.JButton Salvar_jButton;
    private javax.swing.JTextField Water_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField preco_jTextField;
    private javax.swing.JTextField tipo_jTextField;
    // End of variables declaration//GEN-END:variables
}
