/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cadastro;

import View.jTableModel.Fornecedor_jTableModel;
import Entidades.Fornecedor;
import Persistencia.persistenciaFornecedor;
import PersistenciaLista.FornecedorPersistenciaLista;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class CadastrarFornecedor extends javax.swing.JPanel {
    private static persistenciaFornecedor banco = new FornecedorPersistenciaLista ();

    /**
     * Creates new form Fornecedor
     */
    public CadastrarFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Reino = new javax.swing.ButtonGroup();
        Grupo_Fornecedor = new javax.swing.ButtonGroup();
        Sigilo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Button_ReinoA = new javax.swing.JRadioButton();
        Button_ReinoB = new javax.swing.JRadioButton();
        Button_ReinoC = new javax.swing.JRadioButton();
        Button_ReinoD = new javax.swing.JRadioButton();
        Button_ReinoE = new javax.swing.JRadioButton();
        Nome_jTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Button_Viajante = new javax.swing.JRadioButton();
        Button_Mago = new javax.swing.JRadioButton();
        Button_Guilda = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Sigilo_Não = new javax.swing.JRadioButton();
        Sigilo_Sim = new javax.swing.JRadioButton();
        Salvar_jButton = new javax.swing.JButton();
        Cancelar_jButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Fornecedor_jTable = new javax.swing.JTable();
        TipodeFornecedor_jTextField = new javax.swing.JTextField();
        Reino_jTextField = new javax.swing.JTextField();
        Apagar_jButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setMinimumSize(new java.awt.Dimension(600, 450));
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Reino");

        Button_Reino.add(Button_ReinoA);
        Button_ReinoA.setText("Reino A");

        Button_Reino.add(Button_ReinoB);
        Button_ReinoB.setText("Reino B");

        Button_Reino.add(Button_ReinoC);
        Button_ReinoC.setText("Reino C");

        Button_Reino.add(Button_ReinoD);
        Button_ReinoD.setText("Reino D");

        Button_Reino.add(Button_ReinoE);
        Button_ReinoE.setText("Reino E");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de Fornecedor");

        Grupo_Fornecedor.add(Button_Viajante);
        Button_Viajante.setText("Viajante");

        Grupo_Fornecedor.add(Button_Mago);
        Button_Mago.setText("Mago");

        Grupo_Fornecedor.add(Button_Guilda);
        Button_Guilda.setText("Guilda");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Manter Sigilo ");

        Sigilo.add(Sigilo_Não);
        Sigilo_Não.setText("Não");

        Sigilo.add(Sigilo_Sim);
        Sigilo_Sim.setText("Sim");

        Salvar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salvar_jButton.setText("Salvar");
        Salvar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_jButtonActionPerformed(evt);
            }
        });

        Cancelar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar_jButton.setText("Cancelar");
        Cancelar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButtonActionPerformed(evt);
            }
        });

        Fornecedor_jTable.setModel(new Fornecedor_jTableModel(banco.getAll()) );
        jScrollPane2.setViewportView(Fornecedor_jTable);

        Apagar_jButton.setText("Apagar");
        Apagar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apagar_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(Nome_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addComponent(TipodeFornecedor_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(Button_Viajante)
                .addGap(38, 38, 38)
                .addComponent(Button_Mago)
                .addGap(60, 60, 60)
                .addComponent(Button_Guilda))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(Reino_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Button_ReinoA)
                .addGap(20, 20, 20)
                .addComponent(Button_ReinoB)
                .addGap(36, 36, 36)
                .addComponent(Button_ReinoC)
                .addGap(31, 31, 31)
                .addComponent(Button_ReinoD)
                .addGap(19, 19, 19)
                .addComponent(Button_ReinoE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(Sigilo_Sim)
                .addGap(80, 80, 80)
                .addComponent(Sigilo_Não))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(Salvar_jButton)
                .addGap(177, 177, 177)
                .addComponent(Cancelar_jButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Apagar_jButton)
                .addGap(169, 169, 169)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1))
                    .addComponent(Nome_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TipodeFornecedor_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Viajante)
                    .addComponent(Button_Mago)
                    .addComponent(Button_Guilda))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Reino_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_ReinoA)
                    .addComponent(Button_ReinoB)
                    .addComponent(Button_ReinoC)
                    .addComponent(Button_ReinoD)
                    .addComponent(Button_ReinoE))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sigilo_Sim)
                    .addComponent(Sigilo_Não))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salvar_jButton)
                    .addComponent(Cancelar_jButton))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Apagar_jButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Salvar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_jButtonActionPerformed
         Fornecedor novo_Fornecedor = new Fornecedor();
         novo_Fornecedor.setNome(Nome_jTextField.getText());
         novo_Fornecedor.setReino(Reino_jTextField.getText());
         novo_Fornecedor.setTipo(TipodeFornecedor_jTextField.getText());
         banco.inserir(novo_Fornecedor);
         JOptionPane.showMessageDialog(
               Salvar_jButton, "Cadastrado com Sucesso!");
        Cancelar_jButtonActionPerformed(null);
        Fornecedor_jTableModel modelo = (Fornecedor_jTableModel)
                Fornecedor_jTable.getModel();
        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_Salvar_jButtonActionPerformed

    private void Cancelar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancelar_jButtonActionPerformed

    private void Apagar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apagar_jButtonActionPerformed
 int[] linhas = Fornecedor_jTable.getSelectedRows();
        for(int i = linhas.length - 1; i >= 0;i--){
            Fornecedor removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);       
            Fornecedor_jTableModel modelo = 
                (Fornecedor_jTableModel) Fornecedor_jTable.getModel();        
            modelo.fireTableRowsDeleted(0, 1);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_Apagar_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar_jButton;
    private javax.swing.JRadioButton Button_Guilda;
    private javax.swing.JRadioButton Button_Mago;
    private javax.swing.ButtonGroup Button_Reino;
    private javax.swing.JRadioButton Button_ReinoA;
    private javax.swing.JRadioButton Button_ReinoB;
    private javax.swing.JRadioButton Button_ReinoC;
    private javax.swing.JRadioButton Button_ReinoD;
    private javax.swing.JRadioButton Button_ReinoE;
    private javax.swing.JRadioButton Button_Viajante;
    private javax.swing.JButton Cancelar_jButton;
    private javax.swing.JTable Fornecedor_jTable;
    private javax.swing.ButtonGroup Grupo_Fornecedor;
    private javax.swing.JTextField Nome_jTextField;
    private javax.swing.JTextField Reino_jTextField;
    private javax.swing.JButton Salvar_jButton;
    private javax.swing.ButtonGroup Sigilo;
    private javax.swing.JRadioButton Sigilo_Não;
    private javax.swing.JRadioButton Sigilo_Sim;
    private javax.swing.JTextField TipodeFornecedor_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
