/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entidades.Equipamento;
import PersistenciaLista.EquipamentoPersistenciaLista;
import javax.swing.JOptionPane;
import Persistencia.persistenciaEquipamento;

/**
 *
 * @author pascal
 */
public class CadastrarEquipamentos extends javax.swing.JPanel {
    private static persistenciaEquipamento banco = new EquipamentoPersistenciaLista ();

    /**
     * Creates new form CadastrarEquipamentos
     */
    public CadastrarEquipamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Descricao_jTextPane = new javax.swing.JTextPane();
        Cancelar_jButton = new javax.swing.JButton();
        Salvar_jButton = new javax.swing.JButton();
        Fire_jTextField = new javax.swing.JTextField();
        Water_jTextField = new javax.swing.JTextField();
        Air_jTextField = new javax.swing.JTextField();
        Rock_jTextField = new javax.swing.JTextField();
        Defesa_jTextField = new javax.swing.JTextField();
        Ataque_jTextField = new javax.swing.JTextField();
        Level_jTextField = new javax.swing.JTextField();
        Raridade_jTextField = new javax.swing.JTextField();
        tipo_jTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        preco_jTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Equipamento_jTable = new javax.swing.JTable();
        Apagar_jButton = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tipo");
        add(jLabel1);
        jLabel1.setBounds(187, 58, 30, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Level Mínimo");
        add(jLabel2);
        jLabel2.setBounds(79, 106, 88, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ataque");
        add(jLabel3);
        jLabel3.setBounds(89, 151, 49, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Defesa");
        add(jLabel4);
        jLabel4.setBounds(89, 196, 49, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Magia");
        add(jLabel5);
        jLabel5.setBounds(281, 257, 61, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Raridade");
        add(jLabel6);
        jLabel6.setBounds(312, 95, 61, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Descrição");
        add(jLabel7);
        jLabel7.setBounds(304, 151, 69, 17);

        jLabel8.setText("Fogo");
        add(jLabel8);
        jLabel8.setBounds(132, 297, 35, 15);

        jLabel9.setText("Agua");
        add(jLabel9);
        jLabel9.setBounds(244, 297, 36, 15);

        jLabel10.setText("Terra");
        add(jLabel10);
        jLabel10.setBounds(344, 297, 38, 15);

        jLabel11.setText("Ar");
        add(jLabel11);
        jLabel11.setBounds(472, 297, 15, 15);

        jScrollPane3.setViewportView(Descricao_jTextPane);

        add(jScrollPane3);
        jScrollPane3.setBounds(391, 130, 186, 63);

        Cancelar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar_jButton.setText("Cancelar");
        Cancelar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButtonActionPerformed(evt);
            }
        });
        add(Cancelar_jButton);
        Cancelar_jButton.setBounds(138, 379, 94, 27);

        Salvar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salvar_jButton.setText("Salvar");
        Salvar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_jButtonActionPerformed(evt);
            }
        });
        add(Salvar_jButton);
        Salvar_jButton.setBounds(367, 379, 74, 27);
        add(Fire_jTextField);
        Fire_jTextField.setBounds(120, 320, 58, 19);
        add(Water_jTextField);
        Water_jTextField.setBounds(240, 320, 58, 19);
        add(Air_jTextField);
        Air_jTextField.setBounds(460, 320, 58, 19);
        add(Rock_jTextField);
        Rock_jTextField.setBounds(340, 320, 58, 19);
        add(Defesa_jTextField);
        Defesa_jTextField.setBounds(167, 195, 60, 19);
        add(Ataque_jTextField);
        Ataque_jTextField.setBounds(167, 150, 62, 19);
        add(Level_jTextField);
        Level_jTextField.setBounds(167, 105, 62, 19);
        add(Raridade_jTextField);
        Raridade_jTextField.setBounds(391, 94, 116, 19);
        add(tipo_jTextField);
        tipo_jTextField.setBounds(244, 57, 98, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Preço");
        add(jLabel12);
        jLabel12.setBounds(342, 221, 40, 17);

        preco_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preco_jTextFieldActionPerformed(evt);
            }
        });
        add(preco_jTextField);
        preco_jTextField.setBounds(394, 220, 93, 19);

        Equipamento_jTable.setModel(new NovoEquipamento_jTableModel(banco.getAll()) );
        jScrollPane1.setViewportView(Equipamento_jTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(250, 420, 500, 403);

        Apagar_jButton.setText("Apagar");
        Apagar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apagar_jButtonActionPerformed(evt);
            }
        });
        add(Apagar_jButton);
        Apagar_jButton.setBounds(50, 450, 85, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void Salvar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_jButtonActionPerformed
       Equipamento novo_equip = new Equipamento();
       novo_equip.setTipo(tipo_jTextField.getText());
       double preco = Double.parseDouble(preco_jTextField.getText());
       novo_equip.setPreco(preco);
       int atk = Integer.parseInt(Ataque_jTextField.getText());
       novo_equip.setAtk(atk);
       int def = Integer.parseInt(Defesa_jTextField.getText());
       novo_equip.setDef(def);
       novo_equip.setRaridade(Raridade_jTextField.getText());
       int nivel = Integer.parseInt(Level_jTextField.getText());
       novo_equip.setNivelminimo(nivel);
       int fire = Integer.parseInt(Fire_jTextField.getText());
       novo_equip.setMagiaFire(fire);
       int water = Integer.parseInt(Water_jTextField.getText());
       novo_equip.setMagiaWater(water);
       int rock = Integer.parseInt(Rock_jTextField.getText());
       novo_equip.setMagiaRock(rock);
       int air = Integer.parseInt(Air_jTextField.getText());
       novo_equip.setMagiaAir(air);
       novo_equip.setDescricao(Descricao_jTextPane.getText());
       
       banco.inserir(novo_equip);
       JOptionPane.showMessageDialog(
               Salvar_jButton, "Cadastrado com Sucesso!");
        Cancelar_jButtonActionPerformed(null);
        NovoEquipamento_jTableModel modelo = 
        (NovoEquipamento_jTableModel) Equipamento_jTable.getModel();
        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_Salvar_jButtonActionPerformed

    private void Cancelar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancelar_jButtonActionPerformed

    private void preco_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preco_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preco_jTextFieldActionPerformed

    private void Apagar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apagar_jButtonActionPerformed
        int[] linhas = Equipamento_jTable.getSelectedRows();
        
//        int decremento = 0;
//        for(int i = 0; i < linhas.length;i++){
//            Responsavel removido = banco
//                    .getAll().get(linhas[i]-decremento);
        for(int i = linhas.length - 1; i >= 0;i--){
            Equipamento removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);
//            decremento++;
            
            NovoEquipamento_jTableModel modelo = 
                (NovoEquipamento_jTableModel) Equipamento_jTable.getModel();
        
            modelo.fireTableRowsDeleted(0, 1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Apagar_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Air_jTextField;
    private javax.swing.JButton Apagar_jButton;
    private javax.swing.JTextField Ataque_jTextField;
    private javax.swing.JButton Cancelar_jButton;
    private javax.swing.JTextField Defesa_jTextField;
    private javax.swing.JTextPane Descricao_jTextPane;
    private javax.swing.JTable Equipamento_jTable;
    private javax.swing.JTextField Fire_jTextField;
    private javax.swing.JTextField Level_jTextField;
    private javax.swing.JTextField Raridade_jTextField;
    private javax.swing.JTextField Rock_jTextField;
    private javax.swing.JButton Salvar_jButton;
    private javax.swing.JTextField Water_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField preco_jTextField;
    private javax.swing.JTextField tipo_jTextField;
    // End of variables declaration//GEN-END:variables
}
