/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entidades.Fornecedor;
import Persistencia.persistenciaFornecedor;
import PersistenciaLista.FornecedorPersistenciaLista;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class CadastrarFornecedor extends javax.swing.JPanel {
    private static persistenciaFornecedor banco = new FornecedorPersistenciaLista ();

    /**
     * Creates new form Fornecedor
     */
    public CadastrarFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Reino = new javax.swing.ButtonGroup();
        Grupo_Fornecedor = new javax.swing.ButtonGroup();
        Sigilo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Button_ReinoA = new javax.swing.JRadioButton();
        Button_ReinoB = new javax.swing.JRadioButton();
        Button_ReinoC = new javax.swing.JRadioButton();
        Button_ReinoD = new javax.swing.JRadioButton();
        Button_ReinoE = new javax.swing.JRadioButton();
        Nome_jTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Button_Viajante = new javax.swing.JRadioButton();
        Button_Mago = new javax.swing.JRadioButton();
        Button_Guilda = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Sigilo_Não = new javax.swing.JRadioButton();
        Sigilo_Sim = new javax.swing.JRadioButton();
        Salvar_jButton = new javax.swing.JButton();
        Cancelar_jButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Fornecedor_jTable = new javax.swing.JTable();
        TipodeFornecedor_jTextField = new javax.swing.JTextField();
        Reino_jTextField = new javax.swing.JTextField();
        Apagar_jButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setMinimumSize(new java.awt.Dimension(600, 450));
        setName(""); // NOI18N
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");
        add(jLabel1);
        jLabel1.setBounds(120, 40, 41, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Reino");
        add(jLabel2);
        jLabel2.setBounds(329, 184, 57, 22);

        Button_Reino.add(Button_ReinoA);
        Button_ReinoA.setText("Reino A");
        add(Button_ReinoA);
        Button_ReinoA.setBounds(99, 224, 78, 23);

        Button_Reino.add(Button_ReinoB);
        Button_ReinoB.setText("Reino B");
        add(Button_ReinoB);
        Button_ReinoB.setBounds(195, 224, 78, 23);

        Button_Reino.add(Button_ReinoC);
        Button_ReinoC.setText("Reino C");
        add(Button_ReinoC);
        Button_ReinoC.setBounds(308, 224, 78, 23);

        Button_Reino.add(Button_ReinoD);
        Button_ReinoD.setText("Reino D");
        add(Button_ReinoD);
        Button_ReinoD.setBounds(416, 224, 79, 23);

        Button_Reino.add(Button_ReinoE);
        Button_ReinoE.setText("Reino E");
        add(Button_ReinoE);
        Button_ReinoE.setBounds(513, 224, 77, 23);
        add(Nome_jTextField);
        Nome_jTextField.setBounds(204, 38, 378, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de Fornecedor");
        add(jLabel3);
        jLabel3.setBounds(230, 80, 195, 22);

        Grupo_Fornecedor.add(Button_Viajante);
        Button_Viajante.setText("Viajante");
        add(Button_Viajante);
        Button_Viajante.setBounds(189, 131, 84, 23);

        Grupo_Fornecedor.add(Button_Mago);
        Button_Mago.setText("Mago");
        add(Button_Mago);
        Button_Mago.setBounds(308, 131, 64, 23);

        Grupo_Fornecedor.add(Button_Guilda);
        Button_Guilda.setText("Guilda");
        add(Button_Guilda);
        Button_Guilda.setBounds(433, 131, 70, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Manter Sigilo ");
        add(jLabel4);
        jLabel4.setBounds(350, 280, 107, 17);

        Sigilo.add(Sigilo_Não);
        Sigilo_Não.setText("Não");
        add(Sigilo_Não);
        Sigilo_Não.setBounds(450, 310, 53, 23);

        Sigilo.add(Sigilo_Sim);
        Sigilo_Sim.setText("Sim");
        add(Sigilo_Sim);
        Sigilo_Sim.setBounds(320, 310, 50, 23);

        Salvar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salvar_jButton.setText("Salvar");
        Salvar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_jButtonActionPerformed(evt);
            }
        });
        add(Salvar_jButton);
        Salvar_jButton.setBounds(138, 389, 74, 27);

        Cancelar_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cancelar_jButton.setText("Cancelar");
        Cancelar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_jButtonActionPerformed(evt);
            }
        });
        add(Cancelar_jButton);
        Cancelar_jButton.setBounds(367, 389, 94, 27);

        Fornecedor_jTable.setModel(new Fornecedor_jTableModel(banco.getAll()) );
        jScrollPane2.setViewportView(Fornecedor_jTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(310, 440, 453, 403);
        add(TipodeFornecedor_jTextField);
        TipodeFornecedor_jTextField.setBounds(450, 80, 230, 19);
        add(Reino_jTextField);
        Reino_jTextField.setBounds(420, 190, 260, 19);

        Apagar_jButton.setText("Apagar");
        Apagar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apagar_jButtonActionPerformed(evt);
            }
        });
        add(Apagar_jButton);
        Apagar_jButton.setBounds(80, 460, 85, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void Salvar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_jButtonActionPerformed
         Fornecedor novo_Fornecedor = new Fornecedor();
         novo_Fornecedor.setNome(Nome_jTextField.getText());
         novo_Fornecedor.setReino(Reino_jTextField.getText());
         novo_Fornecedor.setTipo(TipodeFornecedor_jTextField.getText());
         banco.inserir(novo_Fornecedor);
         JOptionPane.showMessageDialog(
               Salvar_jButton, "Cadastrado com Sucesso!");
        Cancelar_jButtonActionPerformed(null);
        Fornecedor_jTableModel modelo = (Fornecedor_jTableModel)
                Fornecedor_jTable.getModel();
        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_Salvar_jButtonActionPerformed

    private void Cancelar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancelar_jButtonActionPerformed

    private void Apagar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apagar_jButtonActionPerformed
 int[] linhas = Fornecedor_jTable.getSelectedRows();
        for(int i = linhas.length - 1; i >= 0;i--){
            Fornecedor removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);       
            Fornecedor_jTableModel modelo = 
                (Fornecedor_jTableModel) Fornecedor_jTable.getModel();        
            modelo.fireTableRowsDeleted(0, 1);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_Apagar_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar_jButton;
    private javax.swing.JRadioButton Button_Guilda;
    private javax.swing.JRadioButton Button_Mago;
    private javax.swing.ButtonGroup Button_Reino;
    private javax.swing.JRadioButton Button_ReinoA;
    private javax.swing.JRadioButton Button_ReinoB;
    private javax.swing.JRadioButton Button_ReinoC;
    private javax.swing.JRadioButton Button_ReinoD;
    private javax.swing.JRadioButton Button_ReinoE;
    private javax.swing.JRadioButton Button_Viajante;
    private javax.swing.JButton Cancelar_jButton;
    private javax.swing.JTable Fornecedor_jTable;
    private javax.swing.ButtonGroup Grupo_Fornecedor;
    private javax.swing.JTextField Nome_jTextField;
    private javax.swing.JTextField Reino_jTextField;
    private javax.swing.JButton Salvar_jButton;
    private javax.swing.ButtonGroup Sigilo;
    private javax.swing.JRadioButton Sigilo_Não;
    private javax.swing.JRadioButton Sigilo_Sim;
    private javax.swing.JTextField TipodeFornecedor_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
